---
title: "Bio"
output: 
  html_document:
    toc: true # Add toc
    toc_float: true # keep it on the left
---

---

## Degrees

\

PhD Economics, 2017. Universidad de San Andrés. 

MA Economics, 2008. Universidad de la República.

Bachelor in Economics, 2001. Universidad de la República.

---

## Academic Positions

\

Aggregate Professor, Universidad de la República. Since 2013.

Associate Professor, Universidad de Montevideo. Since 2004.

Other Appointments. Professor, Universidad de La Habana (Economic Regulation, Industrial Organization, Antitrust). Graduate. 2011 –  2013 (Cuba)

Teaching experience. Graduate: Regulation, Institutions, Microeconomics, Industrial Organization, Competition Policy. Undergraduate: Game Theory, Microeconomics, Introduction to Economics, Industrial Organization, Competition Policy.

---

## Professional Activity

\

Consultant for: IADB, CAF, ECLAC, PAHO, and WorldBank.

Private sector consultant in Antitrust, Regulation, Market analysis, Pricing, and Regulatory impact analysis. (Since 2008).


---

## Previous Activity

\

Ministry of Economic and Finance (IADB Project Manager), 2010 – 2013.

Ministry of Economic and Finance (Regulation, Health care public system, Bankruptcy reform), 2005 – 2009.

Ministry of Economic and Finance (Chief Antitrust Economist), 2003 – 2009.

Ministry of Economic and Finance, Dirección General de Comercio (Economic analysis), 2003 – 2010.

Office of Budget and Planning (Regulatory impact analysis, pricing of public services), 2001 – 2003.

---

## Affiliations

\

American Economic Association, Latin American and Caribbean Economic Association.

---

## Personal Interests

\

Music, reading.

***

Last revision: `r format(Sys.Date(), "%B %d, %Y")`. Leandro Zipitría.