---
title: "Mapa mayores de 65 años"
author: "Leandro Zipitria"
date: "24/3/2020"
output: html_document
---

El mapa presenta el número de personas mayores de 65 años por segmento censal, de acuerdo al Censo 2011 del Instituto Nacional de Estadística.
\

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}

library(rgdal)
library(dplyr)
library(leaflet)
library(sf)
library(RColorBrewer)


ShapeCenso2011 <- read_sf("~/Dropbox/Docs/github/UnaImagen/DataBases/Censo2011/ShapeCenso2011_mas65.shp")

```

```{r mapa65mas, echo=FALSE, warning=FALSE, message=FALSE, fig.height = 8, fig.width = 10}


#### ----------------- Grafico -----------------


cuts <- quantile(ShapeCenso2011$N, probs = seq(0,1, by=0.1))
#display.brewer.all()
pal <- colorBin("RdYlBu", domain = ShapeCenso2011$N, bins = cuts, reverse = T)


leaflet(ShapeCenso2011) %>%
   addTiles() %>%
   setView(-56.1, -32, zoom = 7)  %>%
   addPolygons(
      fillColor = ~pal(N),
      weight = 2,
      opacity = 1,
      color = "white",
      dashArray = "3",
      fillOpacity = 0.7,
      highlight = highlightOptions(
         weight = 5,
         color = "#666",
         dashArray = "",
         fillOpacity = 0.7,
         bringToFront = TRUE),
      label = ~N,
      labelOptions = labelOptions(
         style = list("font-weight" = "normal", padding = "3px 8px"),
         textsize = "15px",
         direction = "auto")) %>%
   addLegend(pal = pal, values = ~N, opacity = 0.7, title = NULL,
             position = "bottomright")


```

Fuente: elaborado en base al Censo 2011 del INE.