---
title: "Research"
output: 
  html_document:
    toc: true # Add toc
    toc_float: true # keep it on the left
    includes:
       in_header: ganalitics.html

---

<style type="text/css">

h1.title {
  font-size: 38px;
  text-align: center;
</style>


\
\

My research interests are Industrial Organization and Price Dispersion. 


Links to my research pages at [Google Scholar](https://scholar.google.com/citations?user=UVdbgDwAAAAJ), [SSRN](https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=1038707), and [REPEC](https://ideas.repec.org/e/pzi74.html).


Some codes are in my [Github](http://github.com/LeandroZipitria) page.
  

---

# Books

\


1. 2024. Díaz, Ileana, **Leandro Zipitría** (eds.). *Empresas estatales cubanas. Situación y propuestas de transformación*. Universidad de la Habana y Udelar. Disponible [aquí](files/2024 - Empresas estatales cubanas.pdf).

1. 2016. Domingo, Rosario, Jorge Ponce y **Leandro Zipitría**. *Regulación económica para economías en desarrollo*. Universidad de la República. Disponible [aquí](files/2016.Libro Regulacion FINAL.pdf). También disponible en la siguiente página [web](http://leandro-zipitria.com/libro-regulacion/), y puede ser descargado desde [Github](https://github.com/LeandroZipitria/libro-regulacion).


  

---

# Technical 

\

  
### Published  

\

1. 2026. Borraz, Fernando and **Leandro Zipitría**. [The Border Effect on Prices: The Role of Local Product Availability](files/Disentangling_Border_2026.pdf). Accepted: Journal of Industry, Competition and Trade.

1. 2024. Fernando Borraz, Felipe Carozzi, Nicolás González-Pampillon, and **Leandro Zipitría** [Local Retail Prices, Product Varieties and Neighborhood Change](https://www.aeaweb.org/articles?id=10.1257/pol.20210817&&from=f). AEJ: Economic Policy, 16(1): 1-33. Working paper version [here](files/Borraz_AEJP_2021_R1.pdf).  

1. 2022. Borraz, Fernando and **Leandro Zipitría**. [Varieties as a Source of Law of One Price Deviation](https://www.sciencedirect.com/science/article/abs/pii/S2110701722000543). International Economics, 172: 1-14. WP version [here](files/LOP Version 2021_12_11.pdf). 

1. 2016. Borraz, Fernando, Alberto Cavallo, Roberto Rigobon, and **Leandro Zipitría**. [Distance and Political Boundaries: Estimating Border Effects under Inequality Constraints](https://onlinelibrary.wiley.com/doi/10.1002/ijfe.1517). International Journal of Finance and Economics, 21(1): 3-35. WP version [here](files/2016.Borraz_Cavallo_Rigobon_Zipitria - Distance and political boundaries.pdf).
  
1. 2014. Borraz, Fernando, Juan Dubra, Daniel Ferrés, and **Leandro Zipitría**. [Supermarket Entry and the Survival of Small Stores.](https://link.springer.com/article/10.1007/s11151-013-9379-7) Review of Industrial Organization, vol. 44, Issue 1, 73:93. WP version [here](files/borrazdubraferreszipitria-4th-rr.pdf).
  
1. 2012. Borraz, Fernando and **Leandro Zipitria**. [Retail Price Setting in Uruguay](https://storage.googleapis.com/jnl-lse-j-elaceaj-files/journals/1/articles/141/63e9d285d9db3.pdf). Economia Journal, LACEA, vol. 12(2), Spring, 77-104.
  
1. 2011. Zipitria, Leandro. [Impacto económico del supermercadismo](files/Zipitria2011.pdf). Revista de Ciencias Empresariales y Economía, Universidad de Montevideo, Edición X, págs. 73 – 86.  
  
1. 2011. Bergara, Mario, Jorge Ponce, and **Leandro Zipitria**. [Institutions and Soft Budget Constraints](files/SBC2011.pdf). International Review of Accounting, Banking and Finance, vol. 3(2), págs 41-66.  
  
1. 2010. Caffera, Marcelo, Lucila Arboleya and **Leandro Zipitría**. [¿Estudiar economía te hace más egoísta?](files/2010.Selfish.pdf). Revista de Ciencias Empresariales y Economía, 2010, Edición IX: 29-35.
  
1. 2010. Zipitría, Leandro. [Una aplicación de test de precios al mercado de la cerveza en Uruguay](files/2010.Cerveza.pdf). Revista de Economía, vol. 17, nº1, págs. 149-68, mayo. Banco Central del Uruguay.

\

### Working Papers   

\

1. 2024. Borraz, Fernando and **Leandro Zipitría**. [Assessing long run price convergence in retailing](https://www.econstor.eu/bitstream/10419/289780/1/GLO-DP-1424.pdf), GLO Discussion Paper Series 1424. [Codes](https://github.com/LeandroZipitria/Convergence). (New version "Long-Run Retail Price Dispersion: Dynamics, Market Structure, and Chain Pricing" below).

1. 2018. Czarnievicz, Daniel and **Leandro Zipitría**. [Concentración y precios en cinco mercados minoristas](files/2018.Concentración y precios en cinco mercados minoristas.pdf). Documento de trabajo 06/18, dECON.
  
1. 2016. Rius, Andrés and **Leandro Zipitría**. [Formación y determinación de precios en el Uruguay](https://repositorio.cepal.org/bitstream/handle/11362/39864/S1501314_es.pdf;jsessionid=8C82D69F3FC49D2272777AF8960C1BFB?sequence=1). Series de CEPAL #22.
  
1. 2014. Domingo, Rosario and **Leandro Zipitría**. [Marco regulatorio y empresas públicas en Uruguay](files/2014.Marco regulatorio y empresas publicas en Uruguay.pdf). Documento de trabajo 15/14, dECON.
  
1. 2014. Domingo, Rosario y **Leandro Zipitría**. [La regulación de servicios públicos: el rol de la propiedad](files/2014.La regulacion de empresas publicas - el rol de la propiedad.pdf). Documento de trabajo 13/14, dECON.
  
1. 2013. Bergara, Mario y **Leandro Zipitría**. [Sobre el gobierno corporativo de los organismos multilaterales de crédito](files/2013.Sobre el gobierno corporativo del FLAR dECON 1413.pdf). Documento de trabajo 14/13, dECON.

\
  
### Current Projects  

\

1. 2026. Borraz, Fernando and **Leandro Zipitría**. [Long-Run Retail Price Dispersion: Dynamics, Market Structure, and Chain Pricing](files/2026_Long Run Retail Price Dispersion.pdf). (Submitted).


---

# Non-Technical

\

1. 2023. Zipitría, Leandro. "Los nuevos lineamientos de fusiones de Estados Unidos. Características, contexto y reflexiones para Uruguay", in *Anuario de Derecho de la Competencia*, Fundación de Cultura Universitaria: 263-275.

1. 2023. González Aguila, Ricardo y **Leandro Zipitría**. ["La *Conceptualización* y los incentivos: lo que queda por hacer"](https://cubayeconomia.blogspot.com/2024/01/la-conceptualizacion-y-los-incentivos.html),  Miradas a la economía Cubana. De la *Conceptualización* a la práctica, chapter 3: 35-44. Frederich Ebert Stiftung.

1. 2020. González Aguila, Ricardo y **Leandro Zipitría**. [”¿Pueden las empresas estatales cubanas pagar mayores salarios?”](https://www.jstor.org/stable/10.13169/intejcubastud.12.2.0228), International Journal of Cuban Studies, 12(2): 228-251.

1. 2017. “El rol del sector privado en Cuba”, with Ricardo Torres. In "El emprendimiento: una aproximación internacional al desarrollo económico", chapter 9: 189-218, Editorial de la Universidad de Cantabria.

1. 2011. Zipitría, Leandro. [Sobre la aplicación de la Ley Nº18.159 de promoción y defensa de la competencia](files/2011-la-ley-final1.pdf). La Ley Uruguay, año IV, Nº7, julio.
  
1. 2008. Zipitría, Leandro. [Defensa de la competencia: una breve nota económica](files/2008-capitulo-lz-final-rap.pdf). En "Estudios sobre defensa de la competencia y relaciones de consumo", pp 211-221. Editado por Santiago Pereira y Daniel Rueda. Fondo de Cultura Universitaria.

1. 2003. Bergara, Mario y **Leandro Zipitría**. [Una visión institucional de la legislación de bancarrota](https://www.colibri.udelar.edu.uy/jspui/bitstream/20.500.12008/9605/1/Las%20Reglas%20de%20Juego%20en%20Uruguay.pdf). Capíulo VII del libro "Las reglas de juego en el Uruguay: el entorno institucional y los problemas económicos". Editorial Trilce.


***

Last revision: `r format(Sys.Date(), "%B %d, %Y")`. Leandro Zipitría.
